Repository GreenSpark-greenspark/greenspark-frontend, pull requests merged in 2024-10, with the labels that each got.

#2 init : 폴더 구조 정리, 불필요한 파일 삭제
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  package.json
  postcss.config.mjs
  src/app/layout.tsx
  src/app/my/page.tsx
  src/app/page.tsx
  src/app/power/page.tsx
  src/app/store/page.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/fonts/GeistMonoVF.woff
  src/pages/fonts/GeistVF.woff
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: good first issue

#4 init: width 값 모바일에 맞춰 설정하기
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/globals.css
Labels: good first issue

#7 feat: 하단바 레이아웃 작업
  next.config.mjs
  package.json
  public/icon/nav_appliance.svg
  public/icon/nav_appliance_click.svg
  public/icon/nav_book.svg
  public/icon/nav_book_click.svg
  public/icon/nav_home.svg
  public/icon/nav_home_click.svg
  public/icon/nav_my.svg
  public/icon/nav_my_click.svg
  public/icon/nav_power.svg
  public/icon/nav_power_click.svg
  src/app/layout.tsx
  src/components/bottomNav.tsx
  tsconfig.json
  yarn.lock
Labels: enhancement

#9 fix: 새로고침 시 스타일 적용 안 되는 오류 해결
  next.config.mjs
  src/app/layout.tsx
  src/lib/registry.tsx
Labels: bug

#11 feat: 파워 페이지 레이아웃 작업
  src/app/_component/power/AICharge.tsx
  src/app/_component/power/GraphCharge.tsx
  src/app/_component/power/NowPower.tsx
  src/app/_component/power/PreCharge.tsx
  src/app/_component/power/power.common.css
  src/app/layout.tsx
  src/app/power/page.tsx
Labels: enhancement

#13 Feat: 파워페이지 입력 컴포넌트 세팅
  next.config.mjs
  package.json
  public/icon/power_dropdown.svg
  public/icon/power_plus.svg
  src/app/_component/power/GraphCharge.tsx
  src/app/_component/power/NowPower.tsx
  src/app/_component/power/PowerInput.tsx
  src/app/_component/power/power.common.css
  src/app/_component/powerinput/PowerTable.module.css
  src/app/_component/powerinput/PowerTable.tsx
  src/app/power/page.tsx
  src/app/powerinput/page.tsx
  src/components/bottomNav.module.css
  src/components/bottomNav.tsx
  yarn.lock
Labels: enhancement

#15 feat: 가전 페이지 메인 구현
  public/icon/arrow_left.svg
  public/img/air-conditioner.png
  public/img/refrigerator.png
  public/img/washing-machine.png
  src/app/_component/appliances/MyAppliances.module.css
  src/app/_component/appliances/MyAppliances.tsx
  src/app/appliances/layout.tsx
  src/app/appliances/page.tsx
  src/components/TopBar.module.css
  src/components/TopBar.tsx
  src/mock/appliances.ts
  src/styles/globals.css
  src/utils/getColorfromGrade.ts
Labels: enhancement

#18 feat: 가전 상세 페이지 데이터 불러오기 및 Box 공통 컴포넌트 분리
  src/app/_component/appliances/Appliance.module.css
  src/app/_component/appliances/Appliance.tsx
  src/app/_component/appliances/MyAppliances.module.css
  src/app/_component/appliances/MyAppliances.tsx
  src/app/appliances/(with-my-appliances)/[id]/page.module.css
  src/app/appliances/(with-my-appliances)/[id]/page.tsx
  src/app/appliances/(with-my-appliances)/layout.tsx
  src/app/appliances/(with-my-appliances)/page.tsx
  src/app/appliances/add/page.tsx
  src/components/Box.module.css
  src/components/Box.tsx
  src/mock/appliances.ts
  src/styles/globals.css
  src/styles/reset.css
  src/utils/getColorfromGrade.ts
  src/utils/renderApplianceDetails.ts
Labels: enhancement

#22 Feat: 가전 상세페이지 디자인 퍼블리싱
  src/app/_component/appliances/Appliance.tsx
  src/app/_component/appliances/[id]/BottomView.module.css
  src/app/_component/appliances/[id]/BottomView.tsx
  src/app/_component/appliances/[id]/ItemRow.module.css
  src/app/_component/appliances/[id]/ItemRow.tsx
  src/app/_component/appliances/[id]/TopView.module.css
  src/app/_component/appliances/[id]/TopView.tsx
  src/app/appliances/(with-my-appliances)/[id]/page.module.css
  src/app/appliances/(with-my-appliances)/[id]/page.tsx
  src/utils/renderApplianceDetails.ts
Labels: enhancement

#23 Feat: 파워그래프 퍼블리싱
  package.json
  public/img/graph-default.png
  src/app/_component/power/AICharge.tsx
  src/app/_component/power/BillGraph.tsx
  src/app/_component/power/Graph.tsx
  src/app/_component/power/GraphCharge.tsx
  src/app/_component/power/PowerInput.tsx
  src/app/_component/power/PreCharge.tsx
  src/app/_component/power/UsageGraph.tsx
  src/app/_component/power/graph.common.module.css
  src/app/_component/power/power.common.module.css
  src/mock/powerGraph.ts
  yarn.lock
Labels: enhancement
